services:
  tgbot:
    container_name: tgbot
    image: ghcr.io/jasonkhew96/telegram-search-bot-go:latest
    restart: always
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data.db:/app/data.db

