// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testChatPeers(t *testing.T) {
	t.Parallel()

	query := ChatPeers()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testChatPeersDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatPeer{}
	if err = randomize.Struct(seed, o, chatPeerDBTypes, true, chatPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ChatPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testChatPeersQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatPeer{}
	if err = randomize.Struct(seed, o, chatPeerDBTypes, true, chatPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ChatPeers().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ChatPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testChatPeersSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatPeer{}
	if err = randomize.Struct(seed, o, chatPeerDBTypes, true, chatPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ChatPeerSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ChatPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testChatPeersExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatPeer{}
	if err = randomize.Struct(seed, o, chatPeerDBTypes, true, chatPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ChatPeerExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ChatPeer exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ChatPeerExists to return true, but got false.")
	}
}

func testChatPeersFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatPeer{}
	if err = randomize.Struct(seed, o, chatPeerDBTypes, true, chatPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	chatPeerFound, err := FindChatPeer(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if chatPeerFound == nil {
		t.Error("want a record, got nil")
	}
}

func testChatPeersBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatPeer{}
	if err = randomize.Struct(seed, o, chatPeerDBTypes, true, chatPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ChatPeers().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testChatPeersOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatPeer{}
	if err = randomize.Struct(seed, o, chatPeerDBTypes, true, chatPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ChatPeers().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testChatPeersAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	chatPeerOne := &ChatPeer{}
	chatPeerTwo := &ChatPeer{}
	if err = randomize.Struct(seed, chatPeerOne, chatPeerDBTypes, false, chatPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}
	if err = randomize.Struct(seed, chatPeerTwo, chatPeerDBTypes, false, chatPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = chatPeerOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = chatPeerTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ChatPeers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testChatPeersCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	chatPeerOne := &ChatPeer{}
	chatPeerTwo := &ChatPeer{}
	if err = randomize.Struct(seed, chatPeerOne, chatPeerDBTypes, false, chatPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}
	if err = randomize.Struct(seed, chatPeerTwo, chatPeerDBTypes, false, chatPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = chatPeerOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = chatPeerTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ChatPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func chatPeerBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ChatPeer) error {
	*o = ChatPeer{}
	return nil
}

func chatPeerAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ChatPeer) error {
	*o = ChatPeer{}
	return nil
}

func chatPeerAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ChatPeer) error {
	*o = ChatPeer{}
	return nil
}

func chatPeerBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ChatPeer) error {
	*o = ChatPeer{}
	return nil
}

func chatPeerAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ChatPeer) error {
	*o = ChatPeer{}
	return nil
}

func chatPeerBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ChatPeer) error {
	*o = ChatPeer{}
	return nil
}

func chatPeerAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ChatPeer) error {
	*o = ChatPeer{}
	return nil
}

func chatPeerBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ChatPeer) error {
	*o = ChatPeer{}
	return nil
}

func chatPeerAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ChatPeer) error {
	*o = ChatPeer{}
	return nil
}

func testChatPeersHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ChatPeer{}
	o := &ChatPeer{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, chatPeerDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ChatPeer object: %s", err)
	}

	AddChatPeerHook(boil.BeforeInsertHook, chatPeerBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	chatPeerBeforeInsertHooks = []ChatPeerHook{}

	AddChatPeerHook(boil.AfterInsertHook, chatPeerAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	chatPeerAfterInsertHooks = []ChatPeerHook{}

	AddChatPeerHook(boil.AfterSelectHook, chatPeerAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	chatPeerAfterSelectHooks = []ChatPeerHook{}

	AddChatPeerHook(boil.BeforeUpdateHook, chatPeerBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	chatPeerBeforeUpdateHooks = []ChatPeerHook{}

	AddChatPeerHook(boil.AfterUpdateHook, chatPeerAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	chatPeerAfterUpdateHooks = []ChatPeerHook{}

	AddChatPeerHook(boil.BeforeDeleteHook, chatPeerBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	chatPeerBeforeDeleteHooks = []ChatPeerHook{}

	AddChatPeerHook(boil.AfterDeleteHook, chatPeerAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	chatPeerAfterDeleteHooks = []ChatPeerHook{}

	AddChatPeerHook(boil.BeforeUpsertHook, chatPeerBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	chatPeerBeforeUpsertHooks = []ChatPeerHook{}

	AddChatPeerHook(boil.AfterUpsertHook, chatPeerAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	chatPeerAfterUpsertHooks = []ChatPeerHook{}
}

func testChatPeersInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatPeer{}
	if err = randomize.Struct(seed, o, chatPeerDBTypes, true, chatPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ChatPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testChatPeersInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatPeer{}
	if err = randomize.Struct(seed, o, chatPeerDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(chatPeerColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ChatPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testChatPeersReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatPeer{}
	if err = randomize.Struct(seed, o, chatPeerDBTypes, true, chatPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testChatPeersReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatPeer{}
	if err = randomize.Struct(seed, o, chatPeerDBTypes, true, chatPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ChatPeerSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testChatPeersSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChatPeer{}
	if err = randomize.Struct(seed, o, chatPeerDBTypes, true, chatPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ChatPeers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	chatPeerDBTypes = map[string]string{`ID`: `INTEGER`, `ChatID`: `INTEGER`, `PeerID`: `INTEGER`}
	_               = bytes.MinRead
)

func testChatPeersUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(chatPeerPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(chatPeerAllColumns) == len(chatPeerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ChatPeer{}
	if err = randomize.Struct(seed, o, chatPeerDBTypes, true, chatPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ChatPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, chatPeerDBTypes, true, chatPeerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testChatPeersSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(chatPeerAllColumns) == len(chatPeerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ChatPeer{}
	if err = randomize.Struct(seed, o, chatPeerDBTypes, true, chatPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ChatPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, chatPeerDBTypes, true, chatPeerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(chatPeerAllColumns, chatPeerPrimaryKeyColumns) {
		fields = chatPeerAllColumns
	} else {
		fields = strmangle.SetComplement(
			chatPeerAllColumns,
			chatPeerPrimaryKeyColumns,
		)
		fields = strmangle.SetComplement(fields, chatPeerGeneratedColumns)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ChatPeerSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testChatPeersUpsert(t *testing.T) {
	t.Parallel()
	if len(chatPeerAllColumns) == len(chatPeerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ChatPeer{}
	if err = randomize.Struct(seed, &o, chatPeerDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ChatPeer: %s", err)
	}

	count, err := ChatPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, chatPeerDBTypes, false, chatPeerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ChatPeer struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ChatPeer: %s", err)
	}

	count, err = ChatPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
